### PR TITLE
Build multiarch packages

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @jayfurmanek

**Comment by jakirkham** [comment]
This is now passing! Could someone please take a look? 🙂

**Comment by dopplershift** [comment]
There's no change to the recipe itself here, so the important parts all seem to be around adding the other architectures--which I know nothing about. I can merge, but I don't feel qualified to evaluate anything about what's being added.

**Comment by jakirkham** [comment]
Yeah the different architectures here behave more-or-less the same as this is just pure Python code. Mostly what we are doing is letting Anaconda.org (and therefore Conda) that there are packages that can be installed on these different architectures. Hope that makes sense 🙂

**Comment by jakirkham** [comment]
Thanks Ryan! 😄

**Pull request merged**
