### PR TITLE
flake8: update to 3.0.4

### PR DESCRIPTION
**Pull request by croth1**

### CODE REVIEW

**Comment by croth1** [comment]
@ocefpaf - bumped to 3.0.4 and added myself as maintainer to speed up future updates.

**Comment by ocefpaf** [comment]
Thanks @croth1!

**Comment by croth1** [comment]
@ocefpaf, seems like some uploads failed for obscure reasons:

```
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
```

Can I trigger the upload again without bumping the version number?

**Comment by ocefpaf** [comment]
> Can I trigger the upload again without bumping the version number?

No need to bump as there is no functional change. I will re-start the `CircleCi`.

BTW, as a maintainer, you will get access to `Travis-CI`, not sure about `CircleCI`, but you won't get to `AppVeyor`. (It is unfortunately that not all CIs behave like `Travis-CI`).

I will re-start `CircleCI` now.

**Comment by croth1** [comment]
@ocefpaf @jakirkham, the upload script on macOS does not seem to fail CI if the upload was not successful. Travis came back green but the packages were never uploaded. After a restart everything seems fine.

**Comment by jakirkham** [comment]
Did it have some sort of error message or traceback? Something that can help us to understand why it failed?

**Comment by croth1** [comment]
@jakirkham, I can't spot any failure messages in the logs. See e.g. https://travis-ci.org/conda-forge/flake8-feedstock/jobs/153740245. Travis executed the upload script, but the files never arrived.

**Comment by jakirkham** [comment]
That's the PR build though. Did you see something in the `master` log? One may need to press the little triangles on the side to expand the hidden log output.

Admittedly Travis CI doesn't help us here as they replace the old log in the GUI when restarting. It would be great if they didn't do that. So there might not be much info for us to look at now if the builds were already restarted.

**Comment by jakirkham** [comment]
My suspicion is we were running into issue ( https://github.com/Anaconda-Platform/support/issues/60 ). This is affecting many feedstocks on various CIs so have been tracking that closely on issue ( https://github.com/conda-forge/status/issues/4 ). Not every upload or feedstock seems to be affected. FWICT it is some sort of sporadic failure on the server end.

The fact that Travis CI doesn't fail like other CIs on upload failure is definitely an issue that we need to fix in `conda-smithy`. So have raised it as issue ( https://github.com/conda-forge/conda-smithy/issues/267 ).

**Pull request merged**
